repo:
  url: https://github.com/codeleague/codecoach
  runId: 40
  headCommit: 123qwe123qwe123qwe123qwe123qwe123qwe123q
buildLogFiles:
  - type: tslint
    path: /path/to/log.json
    cwd: /repo/src
output: ./output.json
